### ISSUE TITLE
Errors when running QNLI demo

### ISSUE THREAD

**Issue by aski02** [MadryLab/trak#77]
### Summary
When running the script `trak/examples/qnli.py` on CPU, several errors occur. These errors resolve after downgrading both the `traker` and `transformers` libraries to specific older versions.

---

### 1. Model Loading Error
The script expects model files in `.pt` format, but the `run_glue.py` script from Hugging Face returns SafeTensors.  

---

### 2. Runtime Error
This errors resolves after downgrading the `transformers` library to an older version (f.e. `4.36.0`).
#### Error Trace:
```bash
INFO:TRAK:Using BasicProjector since device is CPU
INFO:TRAK:Using Normal projection
INFO:STORE:No existing model IDs in /Users/niklas/trak_issue/trak/examples/tmp.
INFO:STORE:No existing TRAK scores in /Users/niklas/trak_issue/trak/examples/tmp.
Featurizing..:   0%|                                                                                              | 0/5 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/Users/niklas/trak_issue/trak/examples/qnli.py", line 180, in <module>
    traker.featurize(batch=batch, num_samples=batch[0].shape[0])
  File "/Users/niklas/trak_issue/venv/lib/python3.12/site-packages/trak/traker.py", line 424, in featurize
    grads = self.gradient_computer.compute_per_sample_grad(batch=batch)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/niklas/trak_issue/venv/lib/python3.12/site-packages/trak/gradient_computers.py", line 150, in compute_per_sample_grad
    grads = torch.func.vmap(
            ^^^^^^^^^^^^^^^^
  File "/Users/niklas/trak_issue/venv/lib/python3.12/site-packages/torch/_functorch/apis.py", line 203, in wrapped
    return vmap_impl(
           ^^^^^^^^^^
  File "/Users/niklas/trak_issue/venv/lib/python3.12/site-packages/torch/_functorch/vmap.py", line 331, in vmap_impl
    return _flat_vmap(
           ^^^^^^^^^^^
  File "/Users/niklas/trak_issue/venv/lib/python3.12/site-packages/torch/_functorch/vmap.py", line 479, in _flat_vmap
    batched_outputs = func(*batched_inputs, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/niklas/trak_issue/venv/lib/python3.12/site-packages/torch/_functorch/apis.py", line 399, in wrapper
    return eager_transforms.grad_impl(func, argnums, has_aux, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/niklas/trak_issue/venv/lib/python3.12/site-packages/torch/_functorch/eager_transforms.py", line 1449, in grad_impl
    results = grad_and_value_impl(func, argnums, has_aux, args, kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/niklas/trak_issue/venv/lib/python3.12/site-packages/torch/_functorch/vmap.py", line 48, in fn
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/niklas/trak_issue/venv/lib/python3.12/site-packages/torch/_functorch/eager_transforms.py", line 1407, in grad_and_value_impl
    output = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/niklas/trak_issue/venv/lib/python3.12/site-packages/trak/modelout_functions.py", line 416, in get_output
    logits = ch.func.functional_call(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/niklas/trak_issue/venv/lib/python3.12/site-packages/torch/_functorch/functional_call.py", line 148, in functional_call
    return nn.utils.stateless._functional_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/niklas/trak_issue/venv/lib/python3.12/site-packages/torch/nn/utils/stateless.py", line 298, in _functional_call
    return module(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/niklas/trak_issue/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/niklas/trak_issue/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/niklas/trak_issue/trak/examples/qnli.py", line 76, in forward
    return self.model(input_ids=input_ids,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/niklas/trak_issue/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/niklas/trak_issue/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/niklas/trak_issue/venv/lib/python3.12/site-packages/transformers/models/bert/modeling_bert.py", line 1668, in forward
    outputs = self.bert(
              ^^^^^^^^^^
  File "/Users/niklas/trak_issue/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/niklas/trak_issue/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/niklas/trak_issue/venv/lib/python3.12/site-packages/transformers/models/bert/modeling_bert.py", line 1108, in forward
    extended_attention_mask = _prepare_4d_attention_mask_for_sdpa(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/niklas/trak_issue/venv/lib/python3.12/site-packages/transformers/modeling_attn_mask_utils.py", line 444, in _prepare_4d_attention_mask_for_sdpa
    if not is_tracing and torch.all(mask == 1):
                          ^^^^^^^^^^^^^^^^^^^^
RuntimeError: vmap: It looks like you're either (1) calling .item() on a Tensor or (2) attempting to use a Tensor in some data-dependent control flow or (3) encountering this error in PyTorch internals. For (1): we don't support vmap over calling .item() on a Tensor, please try to rewrite what you're doing with other operations. For (2): If you're doing some control flow instead, we don't support that yet, please shout over at https://github.com/pytorch/functorch/issues/257 . For (3): please file an issue.
```

---

### 3. Attribute Error
Then we get this error which resolves after downgrading `traker` to version `0.2.2`:
#### Error Trace:
```bash
INFO:TRAK:Using BasicProjector since device is CPU
INFO:TRAK:Using Normal projection
INFO:STORE:No existing model IDs in /Users/niklas/trak_issue/trak/examples/tmp.
INFO:STORE:No existing TRAK scores in /Users/niklas/trak_issue/trak/examples/tmp.
Featurizing..: 100%|██████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:04<00:00,  1.21it/s]
Finalizing features for all model IDs..: 100%|████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 56.53it/s]
Scoring..:   0%|                                                                                                  | 0/2 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/Users/niklas/trak_issue/trak/examples/qnli.py", line 191, in <module>
    traker.score(batch=batch, num_samples=batch[0].shape[0])
  File "/Users/niklas/trak_issue/venv/lib/python3.12/site-packages/trak/traker.py", line 572, in score
    grads = self.projector.project(grads, model_id=self.saver.current_model_id)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/niklas/trak_issue/venv/lib/python3.12/site-packages/trak/projectors.py", line 304, in project
    ch.matmul(grads.data, self.proj_matrix, out=sketch)
                          ^^^^^^^^^^^^^^^^
AttributeError: 'BasicProjector' object has no attribute 'proj_matrix'
```

**Comment by Yupei-Du** [comment]
For 2 I think it's because by default Huggingface Transformers now uses SDPA -- in the implementation there're ops not supported by vmap. Using `attn_implementation='eager'` solves the problem for me.

**Comment by kristian-georgiev** [comment]
Great! Can you make a PR please?
